# Generated by Django 3.2.9 on 2021-11-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211129_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Birth',
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True, verbose_name='dob'),
        ),
    ]
