# Generated by Django 3.2.9 on 2021-12-01 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20211201_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersHobbies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.hobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
      

         migrations.RemoveField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='mainapp.UsersHobbies', to='mainapp.Hobby'),
        ),

         migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='related_to', through='mainapp.UsersHobbies', to='mainapp.Hobby'),
        ),
    ]
