# Generated by Django 3.2.9 on 2021-12-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20211201_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='users',
        ),
    ]
