# Generated by Django 3.2.9 on 2021-12-01 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_hobby_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hobby',
        ),
    ]
