# Generated by Django 3.2.9 on 2021-12-01 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20211201_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
    ]
