# Generated by Django 3.2.9 on 2021-12-01 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_user_hobbies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
    ]
